### ISSUE TITLE
Проблема с многосайтовостью

### ISSUE THREAD

**Issue by north-leshiy** [notamedia/console-jedi#25]
Кейс с многосайтовостью, при установке env есть необходимость поменять пути к директориям (поле: "Путь к корневой папке веб-сервера для этого сайта").

Таблица b_lang, переменная DOC_ROOT.

Нужен отдельный раздел в конфиге который это установит.
```php
<?php
return [
	// ...
	'lang' => [
		's1' => [
			'DOC_ROOT' => 'ru/'
		],
		'en' => [
			'DOC_ROOT' => 'en/'
		],
		'de' => [
			'DOC_ROOT' => 'de/'
		],
	]
]
```

**Comment by niksamokhvalov** [comment]
А как это будет использоваться? Зачем Джедаю знание всех документ-рутов?

**Comment by north-leshiy** [comment]
Хотелось бы более быстрого разворачивания окружения на дев машинах, с учетом что не все сидят на вагранте или докере)
Соответственно пути к директориям могут быть разные, а также хост может быть разным для дев/прод указанный в настройках сайта. 
Не все переносится на дев копии в миграциях, иногда на рабочей машине необходим полный апдейт БД с прода, и, в итоге приходится вносить изменения после каждого такого апдейта.

Хотя с другой стороны можно просто не тащить эту таблицу в бекапе БД, настроив параметр единожды.
