### ISSUE TITLE
Управление модулями

### ISSUE THREAD

**Issue by niksamokhvalov** [notamedia/console-jedi#4]
Надо сделать консольные команды для управления модулями, судя по откликам, на них есть спрос.

Список команд:
* `module:register`
* `module:unregister`

Для справки:
1. Не все модули поддерживают режим автоматической установки. Но что с этим делать, пока не понятно.
2. Управление модулями нужно осуществлять через `\Bitrix\Main\ModuleManager`.

**Comment by nook-ru** [comment]
Можно добавить `module:load` для загрузки и установки из *маркетплейс* и `module:remove` для деинсталляции модуля и удаления его папки. Можно даже `module:update` для установки доступных обновлений из *маркетплейс*.

> Не все модули поддерживают режим автоматической установки

Все **типовые сайты** обязаны его поддерживать: они могут устанавливаться при развертывании битрикса, в этом случае их установка проходит без участия пользователя. В документации этот момент обходят стороной и никак не регламентируют автоустановку. Но в общем-то любой модуль, который положили в `/bitrix/modules/` до установки ядра, будет установлен вместе с ядром.

Для интерактивной установки используются методы `DoInstall` и `DoUninstall` в объекте модуля, для автоматической — последовательный вызов `InstallDB`, `InstallEvents`, `InstallFiles`.

Конечно не все сторонние модули корректно такую ситуацию отработают, модуль может не сделать все необходимые ему настройки, а мы об этом даже не узнаем. Как вариант заранее предупреждать о возможных проблемах, о том что ставить нужно только свои модули с корректным установщиком.

> Управление модулями нужно осуществлять через \Bitrix\Main\ModuleManager

Ага. Надо бы проверку минимальной версии ядра добавить или полифил)

**Comment by niksamokhvalov** [comment]
> Надо бы проверку минимальной версии ядра добавить или полифил)
Принято, добавим в `BitrixCommand` проверку версии битры.

С остальным согласен.

**Comment by niksamokhvalov** [comment]
Команды для модулей сделаны, осталось добавить в `BitrixCommand` проверку версии битры.
