### ISSUE TITLE
Добавление своих команд

### ISSUE THREAD

**Issue by xaoc2007** [notamedia/console-jedi#9]
Насколько я понял, опция commands в файле .jedi.php игнорируется.

**Comment by niksamokhvalov** [comment]
Да, есть такой косяк, буквально пару часов назад его поправил :-) Это уже в мастере.

К слову, вы можете регистрировать свои команды через модуль (`cli.php`).

**Comment by xaoc2007** [comment]
Забавно, код один в один такой, как я локально у себя исправил )) Только я еще обработку навернул типа:
```
if(is_object($customCommand) && $customCommand instanceof Command) {
    $this->add($customCommand);
}
```
